language: python
python:
    - "3.5"
sudo: false
env:
    - TOX_ENV=py35-django19
    - TOX_ENV=py34-django19
    - TOX_ENV=py27-django19
    - TOX_ENV=py35-django18
    - TOX_ENV=py34-django18
    - TOX_ENV=py27-django18
    - TOX_ENV=py27-django110
    - TOX_ENV=py35-django110
    - TOX_ENV=py34-django110
    - TOX_ENV=py27-djangomaster
    - TOX_ENV=py34-djangomaster
    - TOX_ENV=py35-djangomaster
matrix:
    fast_finish: true
    allow_failures:
      - env: TOX_ENV=py27-djangomaster
      - env: TOX_ENV=py34-djangomaster
      - env: TOX_ENV=py35-djangomaster
install:
    - pip install tox
script:
    - tox -e $TOX_ENV
